### ISSUE TITLE
Data and Model files.

### ISSUE THREAD

**Issue by abhtfrnd** [AzizCode92/text_mining_project#1]
Hi, can you please provide the data and model files that you used in your project.
And also if you have ran https://github.com/attardi/deepnl/issues/50 this code then what is the 'words.txt' and 'vectors.txt' there and how to get these files.

**Comment by AzizCode92** [comment]
Hi, the dataset we used is provided here [SemEval Dataset](http://alt.qcri.org/semeval2016/task4/index.php?id=data-and-tools).
For the question about the `words.txt` and `vectors.txt ` I invite you to read the documentation in the repo there so you can understand their utilities.
Good luck,
